'use client';
import './ideas.css';
import DevelopDirection from './DevelopDirection';
import { developDirection } from '../../lib/creative-studio/development-brief';
import { emptyComparison, type CreativeContent } from '../../lib/creative-studio/content';
import { useEffect, useState } from 'react';
import { ADVERTISING_TYPES, AWARENESS_OPTIONS, DEFAULT_IDEA, FORMATS, SUGGESTIONS, acceptSuggestion, editIdea, switchIdeaFormat, ideaScene, recommend, suggestionSource, type Idea } from '../../lib/creative-studio/ideas';
import { referencesForStage } from '../../lib/creative-studio/reference-catalog';
import { STAGES, type Scene, type Stage } from '../../lib/creative-studio/model';
import type { Direction } from '../../lib/creative-studio/directions';
export default function IdeaBuilder({saved,disabled,onDirty,onSave,onPlanningOnly}:{saved?:Direction;disabled:boolean;onDirty:(v:boolean)=>void;onSave:(idea:Idea,apply:boolean)=>void;onPlanningOnly:(v:boolean)=>void}) {
 const [idea,setIdea]=useState<Idea>(saved?.idea??DEFAULT_IDEA);
 const [help,setHelp]=useState('');
 const dirty=JSON.stringify(idea)!==JSON.stringify(saved?.idea??DEFAULT_IDEA);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 useEffect(()=>{onPlanningOnly(idea.format==='process'||!!idea.activeDevelopment);},[idea.format,idea.activeDevelopment,onPlanningOnly]);
 const change=<K extends keyof Idea>(key:K,value:Idea[K])=>setIdea(i=>editIdea(i,key,value));
 const rec=recommend(idea);const stage=idea.stageOverride??rec.stage;
 const format=FORMATS.find(f=>f.id===idea.format)!;
 const scene:Scene|null=ideaScene(idea);
 const helpField=(field:string)=> <><button type="button" className="cs-text-button" onClick={()=>setHelp(help===field?'':field)}>Help me with {field}</button>{help===field&&<div className="cs-idea-help"><p>Saved EIC source suggestions — review before accepting. Website research: <strong>Not connected</strong>.</p>{SUGGESTIONS.filter(s=>s.field===field).map(s=>{const source=suggestionSource(s.sourceId);return <div key={s.id}><p><strong>{s.value}</strong></p><p>{s.why}</p><a href={source.url} target="_blank" rel="noreferrer">Source: {source.title}</a><p className="cs-help">{source.note}</p><button className="cs-button cs-secondary" onClick={()=>setIdea(acceptSuggestion(idea,s.id))}>Accept suggestion</button><button className="cs-text-button" onClick={()=>setHelp('')}>Not now — leave pending</button></div>})}{!SUGGESTIONS.some(s=>s.field===field)&&<p>Write this in your own words. No sourced suggestion is available; we will not fill it in for you.</p>}</div>}</>;
 return <section className="cs-panel cs-controls cs-idea-builder" aria-label="Idea builder">
 <div className="cs-eyebrow">BUILD YOUR CREATIVE</div><h2>Start with what you are advertising</h2><p>Answer a few plain-language questions, choose a visual style, and add only the inputs that style needs.</p>
 <p className="cs-help"><strong>EIC white-label pilot only.</strong> Saved offer and examples are EIC-specific, not generic client facts. Business notes below do not replace that offer.</p>
 <fieldset disabled={disabled}>
 <div className="cs-idea-modes"><button className="cs-button cs-secondary" aria-pressed={idea.mode==='guided'} onClick={()=>change('mode','guided')}>Guide me</button><button className="cs-button cs-secondary" aria-pressed={idea.mode==='direct'} onClick={()=>change('mode','direct')}>I know my style</button></div>
 {idea.mode==='guided'&&<nav className="cs-idea-modes" aria-label="Idea steps">{['What you are advertising','Audience','Visual style'].map((label,n)=><button className="cs-text-button" key={label} aria-current={idea.step===n?'step':undefined} onClick={()=>change('step',n)}>{n+1}. {label}</button>)}</nav>}
 {(idea.mode==='guided'&&idea.step===0)&&<><h3>What are you advertising?</h3><div className="cs-idea-cards cs-compact-cards">{Object.entries(ADVERTISING_TYPES).map(([id,name])=><button key={id} aria-pressed={(idea.advertisingType??'')===id} onClick={()=>change('advertisingType',id as NonNullable<Idea['advertisingType']>)}>{name}</button>)}</div><label>Tell us what it is and what makes it useful<textarea aria-label="What are you advertising?" maxLength={280} placeholder="For example: a free paid-media plan for agency owners" value={idea.advertisingSubject??''} onChange={e=>change('advertisingSubject',e.target.value)}/></label><button className="cs-button cs-primary" disabled={!idea.advertisingType||!(idea.advertisingSubject??'').trim()} onClick={()=>change('step',1)}>Next: audience</button></>}
 {(idea.mode==='guided'&&idea.step===1)&&<><h3>Who should see it?</h3><label>Describe the people you want to reach<textarea aria-label="Who should see it?" maxLength={280} placeholder="For example: agency owners who want to add paid media" value={idea.audience} onChange={e=>change('audience',e.target.value)}/></label>{helpField('audience')}<h3>What do they already know?</h3><div className="cs-awareness-cards">{AWARENESS_OPTIONS.map(option=><button key={option.id} aria-pressed={idea.awareness===option.id} onClick={()=>change('awareness',option.id)}><strong>{option.label}</strong><small>{option.description}</small></button>)}</div><button className="cs-button cs-primary" disabled={!idea.audience.trim()||idea.awareness==='unknown'} onClick={()=>change('step',2)}>Choose a visual style</button></>}
 {(idea.mode==='direct'||idea.step===2)&&<>
 <div className="cs-idea-recommendation"><strong>{stage?'Message approach selected from audience awareness':'Audience context needed'}</strong><p>{rec.reason}</p><small>This rule is automatic and does not limit your visual choices.</small></div>
 <details className="cs-idea-advanced" aria-label="Advanced idea settings"><summary>Advanced · funnel override and reference catalog</summary><label>Manual funnel override<select aria-label="Funnel choice" value={idea.stageOverride??''} onChange={e=>change('stageOverride',(e.target.value||null) as Stage|null)}><option value="">Use audience awareness</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><div className="cs-planning-option"><strong>Process walkthrough · planning only</strong><p>Capture the real steps first. Artwork stays unavailable until an approved artifact and renderer exist.</p><button type="button" className="cs-button cs-secondary" aria-pressed={idea.format==='process'} onClick={()=>setIdea(i=>switchIdeaFormat(i,'process'))}>Plan this direction</button></div><details aria-label="Reference idea catalog"><summary>17 reference ideas · planning references</summary><p>Publisher-owned pages and archived visual executions, not verified paid delivery or winners. Read-only guidance: no external claims enter your draft.</p>{referencesForStage(stage).map(e=><details key={e.id} data-reference={e.id}><summary>{e.title} · reference-only</summary><p><strong>Communication job:</strong> {e.communicationJob}</p><p><strong>Why it fits:</strong> {e.rationale}</p><p><strong>Format:</strong> {e.format}. {e.visualTreatment}</p><h4>Required inputs</h4><ul>{e.requiredInputs.map(t=><li key={t}>{t}</li>)}</ul><h4>Claim boundaries</h4><ul>{e.claimConstraints.map(t=><li key={t}>{t}</li>)}</ul>{e.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.publisher}: {s.title}</a><br/>{s.limitations}</p>)}{e.id!=='ve-p1-9'?<button className="cs-button cs-secondary" onClick={()=>setIdea(i=>developDirection(i,e.id))}>Develop this direction</button>:<p>Negative counterexample — cannot be adopted.</p>}</details>)}</details></details>
 {idea.activeDevelopment&&<DevelopDirection key={idea.activeDevelopment} idea={idea} onChange={setIdea}/>}
 {!idea.activeDevelopment&&<><h3>Choose a visual style</h3><div className="cs-idea-cards cs-style-cards">{FORMATS.filter(f=>f.id!=='process').map(f=><button key={f.id} data-format={f.id} aria-pressed={idea.format===f.id} onClick={()=>setIdea(i=>switchIdeaFormat(i,f.id))}><span className="cs-style-preview" data-style={f.id} aria-hidden="true"><i/><i/><i/></span><strong>{f.name}</strong><p>{f.idea}</p><small>{f.capability}</small>{rec.stage&&rec.formats.includes(f.id)&&<span className="cs-style-fit">Good fit for this audience</span>}</button>)}</div>
 <h3>{format.name}: inputs that matter</h3><p>{format.required}</p>
 {idea.format!=='process'&&<><label>{idea.format==='notes'?'Note':'Comparison'} headline<textarea aria-label={idea.format==='notes'?'Note headline':'Comparison headline'} maxLength={90} value={idea.headline} onChange={e=>change('headline',e.target.value)}/></label>{helpField('headline')}<label>{idea.format==='notes'?'Note':'Comparison'} closing line<input aria-label={idea.format==='notes'?'Note closing line':'Comparison closing line'} maxLength={38} value={idea.closing} onChange={e=>change('closing',e.target.value)}/></label>{helpField('closing')}{idea.format==='notes'&&<label>Note body<textarea aria-label="Note body" maxLength={600} value={idea.content?.kind==='note'?idea.content.body:''} onChange={e=>change('content',{kind:'note',body:e.target.value})}/></label>}<p className="cs-help">User copy is unverified. Source pins do not verify these words. No invented testimonials or universal competitor claims.</p></>}
 {idea.format==='comparison'&&<ComparisonInputs value={idea.content?.kind==='comparison'?idea.content:emptyComparison()} onChange={v=>change('content',v)}/>}
 {idea.format==='process'&&<p role="status">Needs input + renderer. Save this idea for planning, or choose Notes. No unrelated template will be composed.</p>}
 <p className="cs-help">{idea.accepted.length} source suggestions explicitly accepted. All other inputs remain manual or pending.</p>
 <button className="cs-button cs-primary" disabled={!scene||!stage||!idea.content||(idea.mode==='guided'&&idea.advertisingSubject!==undefined&&(!idea.advertisingSubject.trim()||!idea.audience.trim()))} onClick={()=>onSave(idea,true)}>Use this idea</button></>}
 </>}
 <div className="cs-save-row"><span className="cs-help">{dirty?'Unsaved idea decisions':'Idea decisions saved or unchanged'} · Saves separately from artwork.</span><button className="cs-button cs-secondary" onClick={()=>onSave(idea,false)}>Save idea decisions</button></div>
 </fieldset></section>;
}

function ComparisonInputs({value,onChange}:{value:Extract<CreativeContent,{kind:'comparison'}>;onChange:(v:CreativeContent)=>void}) {
 const cell=(i:number,side:'left'|'right',text:string)=>onChange({...value,rows:value.rows.map((r,n)=>n===i?{...r,[side]:{...r[side],text,status:'user-claimed',reviewNote:undefined}}:r)});
 return <div><label>Left heading<input aria-label="Left heading" maxLength={32} value={value.leftHeading} onChange={e=>onChange({...value,leftHeading:e.target.value})}/></label><label>Right heading<input aria-label="Right heading" maxLength={32} value={value.rightHeading} onChange={e=>onChange({...value,rightHeading:e.target.value})}/></label>{value.rows.map((r,i)=><div key={i}><label>Benefit {i+1}<input aria-label={`Benefit ${i+1}`} maxLength={36} value={r.label} onChange={e=>onChange({...value,rows:value.rows.map((x,n)=>n===i?{...x,label:e.target.value}:x)})}/></label>{(['left','right'] as const).map(side=><label key={side}>{side} {i+1}<input aria-label={`${side} ${i+1}`} maxLength={72} value={r[side].text} onChange={e=>cell(i,side,e.target.value)}/><small>{r[side].status} · {r[side].sourceIds.length} source receipts</small></label>)}</div>)}<button className="cs-text-button" disabled={value.rows.length>=5} onClick={()=>onChange({...value,rows:[...value.rows,emptyComparison().rows[0]]})}>Add benefit row</button><button className="cs-text-button" disabled={value.rows.length<=3} onClick={()=>onChange({...value,rows:value.rows.slice(0,-1)})}>Remove last row</button></div>;
}
