export type CaseStudy = {
  slug: string;
  client: string;
  title: string;
  description: string;
  image: string;
  industry: string;
  primaryMetric: string;
  primaryMetricLabel: string;
  metrics: Array<{ value: string; label: string }>;
  challenges: string[];
  solutions: Array<{ title: string; copy: string }>;
  results: string[];
  conclusion: string;
};

export const caseStudies: CaseStudy[] = [
  {
    slug: 'prepass-business-intelligence-growth',
    client: 'PrePass',
    title: 'From Guesswork to Growth: The BI Strategy That Changed Everything for PrePass',
    description:
      'How a complete business intelligence system, a clear qualified-lead definition, and campaign restructuring helped PrePass scale qualified lead volume while sharply reducing cost.',
    image: '/proof/prepass-case-study-thumb.jpg',
    industry: 'Transportation technology',
    primaryMetric: '99.8%',
    primaryMetricLabel: 'reduction in cost per qualified lead',
    metrics: [
      { value: '1,200+', label: 'qualified leads in June' },
      { value: '5', label: 'qualified leads in January' },
      { value: '1,336x', label: 'growth in qualified opportunities reported in the source study' },
    ],
    challenges: [
      'High campaign costs with little to no qualified return.',
      'No visibility into the business results generated by advertising.',
      'No shared definition of what counted as a qualified lead.',
    ],
    solutions: [
      {
        title: 'Complete BI system',
        copy: 'EIC deployed dashboards and real-time performance indicators so campaign decisions could be tied to business outcomes.',
      },
      {
        title: 'Qualified-lead definition',
        copy: 'The team established a clear qualification standard centered on companies with large truck fleets.',
      },
      {
        title: 'Campaign restructuring',
        copy: 'Every active campaign was reviewed and restructured around the new measurement and qualification framework.',
      },
      {
        title: 'Data-driven optimization',
        copy: 'Ongoing optimizations were based on qualified performance data rather than top-line lead volume alone.',
      },
    ],
    results: [
      'Qualified lead volume grew from an average of 5 in January to more than 1,200 in June within the client’s ISP 4 segment.',
      'The source case study reports a 99.8% reduction in cost per qualified lead since the project began.',
      'The new reporting layer gave the client real-time visibility into lead quality and campaign efficiency.',
    ],
    conclusion:
      'A clear strategy and a robust BI infrastructure turned an inefficient campaign program into a data-driven marketing operation focused on qualified outcomes.',
  },
  {
    slug: 'spartaco-full-funnel-growth',
    client: 'Spartaco Tool Group',
    title: 'The Strategy Shift That Unlocked Spartaco’s Digital Potential',
    description:
      'How full-funnel lead generation, reliable tracking, campaign restructuring, and business intelligence improved both eCommerce return and lead-generation efficiency.',
    image: '/proof/spartaco-case-study-thumb.jpg',
    industry: 'Industrial tools',
    primaryMetric: '696.49%',
    primaryMetricLabel: 'increase in ROAS',
    metrics: [
      { value: '83.5%', label: 'reduction in cost per lead' },
      { value: '$24.42', label: 'starting cost per lead' },
      { value: '$4.03', label: 'ending cost per lead' },
    ],
    challenges: [
      'No reliable system for measuring campaign performance or attributing results.',
      'No structured lead-generation program across the portfolio of brands.',
      'Digital activity was not producing meaningful eCommerce revenue.',
    ],
    solutions: [
      {
        title: 'B2B lead generation',
        copy: 'EIC launched targeted lead campaigns and added strategic website forms, including Request Demo paths, to capture qualified demand.',
      },
      {
        title: 'Lead and sales tracking',
        copy: 'Reliable tracking connected conversions to their sources and made channel performance measurable.',
      },
      {
        title: 'Campaign restructuring',
        copy: 'Active campaigns were overhauled across targeting, creative, and keyword strategy.',
      },
      {
        title: 'Complete BI system',
        copy: 'Custom dashboards gave each brand real-time visibility into the metrics used for budget and optimization decisions.',
      },
    ],
    results: [
      'eCommerce ROAS increased from 0.57 to 4.54 over the study period, a 696.49% increase.',
      'Cost per lead fell from $24.42 to $4.03, an 83.5% reduction.',
      'Spartaco gained a unified view of digital performance across Jameson Tools, Huskie Tools, and Ronin Power Ascender.',
    ],
    conclusion:
      'A unified strategy built around tracking, business intelligence, lead capture, and continuous optimization turned a scattered marketing operation into a more predictable growth engine.',
  },
  {
    slug: 'chamfr-roas-growth',
    client: 'Chamfr',
    title: 'Unlocking Growth: The Strategy Behind Chamfr’s Surge in ROAS',
    description:
      'How product-level segmentation, new campaign formats, and performance-driven optimization helped Chamfr replace an unstable, one-dimensional account structure with scalable growth.',
    image: '/proof/chamfr-case-study-thumb.jpg',
    industry: 'Medical device marketplace',
    primaryMetric: '900%',
    primaryMetricLabel: 'increase in ROAS in less than two months',
    metrics: [
      { value: '11.34', label: 'new-campaign ROAS in June' },
      { value: '0.12', label: 'legacy-campaign ROAS in June' },
      { value: '94x+', label: 'more revenue from new campaigns than legacy campaigns in June' },
    ],
    challenges: [
      'Existing campaigns produced unstable returns that often fell below sustainable levels.',
      'Media spend was concentrated in Shopping campaigns with limited format testing or segmentation.',
    ],
    solutions: [
      {
        title: 'Product-category structure',
        copy: 'Campaigns were separated by product category to improve bidding, budget control, and performance visibility.',
      },
      {
        title: 'New campaign formats',
        copy: 'The strategy expanded beyond Shopping into Search, Performance Max, and complementary formats to improve funnel coverage.',
      },
      {
        title: 'Parallel validation',
        copy: 'New campaigns ran alongside the legacy structure for two months so performance could be compared directly.',
      },
      {
        title: 'Performance-driven optimization',
        copy: 'Budgets and tactics were continuously adjusted using real-time performance by product and campaign type.',
      },
    ],
    results: [
      'In June, new campaigns produced an 11.34 ROAS while legacy campaigns produced a 0.12 ROAS.',
      'Consolidated account ROAS increased from 0.59 in May to 8.88 in June and remained strong at 8.45 in July.',
      'The source case study reports a 900% ROAS increase in less than two months after restructuring.',
    ],
    conclusion:
      'Structure, segmentation, broader campaign formats, and real-time optimization replaced a one-dimensional setup with a tested acquisition model designed to scale.',
  },
];

export function getCaseStudy(slug: string) {
  return caseStudies.find((study) => study.slug === slug);
}
