-- Shared creative test registry.
-- The initial production pilot is isolated to client_key = 'goodgame'.
-- Other clients must be migrated explicitly and individually after pilot approval.

create table if not exists public.creative_tests (
  id bigint generated by default as identity primary key,
  test_key text not null,
  client_key text not null,
  initiative_key text not null,

  source_insight_table text,
  source_insight_id bigint,
  source_period_start date,
  source_period_end date,
  parent_test_id bigint references public.creative_tests(id) on delete set null,

  title text not null,
  hypothesis text not null default '',
  primary_variable text,
  creative_format text,
  control_description text,

  north_star_metric text not null,
  north_star_direction text not null default 'maximize'
    check (north_star_direction in ('maximize', 'minimize')),
  evidence_threshold jsonb not null default '{}'::jsonb,

  impact_score smallint check (impact_score between 1 and 5),
  speed_score smallint check (speed_score between 1 and 5),
  confidence_score smallint check (confidence_score between 1 and 5),
  effort_score smallint check (effort_score between 1 and 5),
  priority_score numeric(5, 2) generated always as (
    case
      when impact_score is null
        or speed_score is null
        or confidence_score is null
        or effort_score is null
      then null
      else (
        impact_score * 40
        + speed_score * 30
        + confidence_score * 20
        + (6 - effort_score) * 10
      ) / 5.0
    end
  ) stored,
  priority_reason text,

  status text not null default 'recommended'
    check (status in (
      'recommended',
      'approved',
      'in_production',
      'launched',
      'evaluating',
      'concluded',
      'declined',
      'cancelled'
    )),
  owner_name text,
  approved_by text,
  approved_at timestamptz,
  production_started_at timestamptz,
  launched_at timestamptz,
  concluded_at timestamptz,

  linked_ad_ids text[] not null default '{}'::text[],
  control_ad_ids text[] not null default '{}'::text[],
  preview_urls jsonb not null default '[]'::jsonb,

  current_evaluation jsonb not null default '{}'::jsonb,
  final_result jsonb not null default '{}'::jsonb,
  verdict text check (verdict is null or verdict in (
    'expand',
    'iterate',
    'retire',
    'inconclusive'
  )),
  learning text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (client_key, initiative_key, test_key)
);

create index if not exists creative_tests_client_initiative_status_idx
  on public.creative_tests (client_key, initiative_key, status);

create index if not exists creative_tests_source_insight_idx
  on public.creative_tests (source_insight_table, source_insight_id);

create or replace function public.set_creative_tests_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists creative_tests_set_updated_at on public.creative_tests;
create trigger creative_tests_set_updated_at
before update on public.creative_tests
for each row execute function public.set_creative_tests_updated_at();

alter table public.creative_tests enable row level security;

comment on table public.creative_tests is
  'Cross-client creative test lifecycle registry. Initial approved pilot scope: Good Game eCommerce only.';
