begin;

create table if not exists public.medibrane_meta (
  id bigint generated by default as identity primary key,
  date date not null,
  account_id text not null check (account_id = '1532993340786486'),
  campaign_id text not null,
  campaign_name text not null,
  ad_channel text not null default 'Meta' check (ad_channel = 'Meta'),
  impressions bigint not null default 0 check (impressions >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  link_clicks bigint not null default 0 check (link_clicks >= 0),
  cost numeric(14, 2) not null default 0 check (cost >= 0),
  conversions numeric(14, 2) not null default 0 check (conversions >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (date, campaign_id)
);

create index if not exists medibrane_meta_date_idx
  on public.medibrane_meta (date);

create index if not exists medibrane_meta_campaign_date_idx
  on public.medibrane_meta (campaign_id, date);

alter table public.medibrane_meta enable row level security;
revoke all on table public.medibrane_meta from public, anon, authenticated;
grant select, insert, update, delete on table public.medibrane_meta to service_role;
grant usage, select on sequence public.medibrane_meta_id_seq to service_role;

comment on table public.medibrane_meta is
  'Daily campaign-level Meta Ads performance for Medibrane account 1532993340786486; currency ILS and account timezone Asia/Jerusalem.';
comment on column public.medibrane_meta.conversions is
  'Meta lead actions: canonical lead aggregate with lead-specific aliases as fallbacks; aliases are never summed and traffic/engagement actions are excluded.';

commit;
