begin;

create table if not exists public.medibrane_google (
  id bigint generated by default as identity primary key,
  date date not null,
  account_id text not null check (account_id = '8502300209'),
  campaign_id text not null,
  campaign_name text not null,
  campaign_status text,
  campaign_type text,
  ad_channel text not null default 'Google' check (ad_channel = 'Google'),
  currency text not null default 'USD' check (currency = 'USD'),
  impressions bigint not null default 0 check (impressions >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  link_clicks bigint not null default 0 check (link_clicks >= 0),
  cost numeric(18, 6) not null default 0 check (cost >= 0),
  conversions numeric(14, 2) not null default 0 check (conversions >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (date, campaign_id)
);

alter table public.medibrane_google
  alter column cost type numeric(18, 6);

create index if not exists medibrane_google_date_idx
  on public.medibrane_google (date);

create index if not exists medibrane_google_campaign_date_idx
  on public.medibrane_google (campaign_id, date);

alter table public.medibrane_google enable row level security;
revoke all on table public.medibrane_google from public, anon, authenticated;
grant select, insert, update, delete on table public.medibrane_google to service_role;
grant usage, select on sequence public.medibrane_google_id_seq to service_role;

comment on table public.medibrane_google is
  'Daily campaign-level Google Ads performance for Medibrane account 8502300209; currency USD and account timezone America/Los_Angeles.';
comment on column public.medibrane_google.conversions is
  'Daily campaign conversions from Medibrane | HubSpot Contact Form Submit | GTM (conversion action 7769953817); engagement and legacy actions are excluded.';

commit;
