begin;

create table if not exists public.nsi_linkedin_creatives (
  id bigint generated by default as identity primary key,
  creative_id text not null,
  creative_urn text not null default '',
  campaign_id text not null default '',
  campaign_name text not null default '',
  ad_name text not null default '',
  period_start date not null,
  period_end date not null,
  as_of_date date not null,
  impressions numeric not null default 0,
  clicks numeric not null default 0,
  spend numeric not null default 0,
  leads numeric not null default 0,
  primary_text text not null default '',
  headline text not null default '',
  destination_url text not null default '',
  media_urn text not null default '',
  media_type text not null default '',
  source_media_url text not null default '',
  permanent_media_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nsi_linkedin_creatives_creative_id_key unique (creative_id)
);

create index if not exists nsi_linkedin_creatives_as_of_date_idx
  on public.nsi_linkedin_creatives (as_of_date desc);
create index if not exists nsi_linkedin_creatives_campaign_id_idx
  on public.nsi_linkedin_creatives (campaign_id);

alter table public.nsi_linkedin_creatives enable row level security;

comment on table public.nsi_linkedin_creatives is
  'Latest rolling 30-day LinkedIn creative performance and presentation data for NSI Ads analysis.';
comment on column public.nsi_linkedin_creatives.permanent_media_url is
  'Public Supabase Storage URL refreshed by the NSI LinkedIn creative ingestion workflow.';

commit;
