import test from 'node:test';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';
import {createStudioPrivateStorage,StudioStorageError,type StudioPrivateObjectTransport,type StudioStorageLocator} from './creative-studio-private-storage.ts';
const ownerId=randomUUID();const context={tenantId:'eicagency' as const,ownerId};const locator:StudioStorageLocator={ownerId,projectId:randomUUID(),versionId:randomUUID(),placementId:'1:1',jobId:randomUUID(),leaseToken:randomUUID()};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=','base64');
const meta={sha256:createHash('sha256').update(png).digest('hex'),sizeBytes:png.length,width:1,height:1,mimeType:'image/png' as const};
const code=(value:string)=>(e:unknown)=>e instanceof StudioStorageError&&e.code===value;
function fixture(){const records=new Map<string,Blob>();const calls:string[]=[];const transport:StudioPrivateObjectTransport={async upload(bucket,key,bytes,options){calls.push('upload');assert.equal(bucket,'creative-studio-private');assert.equal(options.upsert,false);assert.equal(options.contentType,'image/png');if(records.has(key))return{error:new Error('sensitive backend collision')};records.set(key,new Blob([Uint8Array.from(bytes)],{type:options.contentType}));return{error:null};},async download(bucket,key){calls.push('download');assert.equal(bucket,'creative-studio-private');return{data:records.get(key)??null,error:null};}};return{records,calls,transport,store:createStudioPrivateStorage(context,transport)};}
test('PNG roundtrip and create-only immutable attempt key; no keys returned to caller',async()=>{const f=fixture();assert.equal(await f.store.upload(locator,png,meta),undefined);assert.deepEqual(await f.store.download(locator,meta),png);assert.equal([...f.records.keys()][0],['eicagency',ownerId,locator.projectId,locator.versionId,locator.placementId,locator.jobId,locator.leaseToken].join('/'));await assert.rejects(f.store.upload(locator,png,meta),code('unavailable'));assert.deepEqual(await f.store.download(locator,meta),png);});
test('cross-owner and path injection rejected before storage',async()=>{const f=fixture();await assert.rejects(f.store.download({...locator,ownerId:randomUUID()},meta),code('denied'));await assert.rejects(f.store.upload({...locator,projectId:'../escape'},png,meta),code('invalid'));assert.deepEqual(f.calls,[]);});
test('invalid bytes/hash/dimensions rejected before upload',async()=>{const f=fixture();await assert.rejects(f.store.upload(locator,png,{...meta,sha256:'0'.repeat(64)}),code('integrity'));await assert.rejects(f.store.upload(locator,png,{...meta,width:2}),code('integrity'));await assert.rejects(f.store.upload(locator,Buffer.from('not-png'),meta),code('integrity'));assert.deepEqual(f.calls,[]);});
test('corrupt download and wrong MIME rejected',async()=>{const f=fixture();await f.store.upload(locator,png,meta);const key=[...f.records.keys()][0];const corrupt=Buffer.from(png);corrupt[corrupt.length-1]^=1;f.records.set(key,new Blob([corrupt],{type:'image/png'}));await assert.rejects(f.store.download(locator,meta),code('integrity'));f.records.set(key,new Blob([png],{type:'text/html'}));await assert.rejects(f.store.download(locator,meta),code('integrity'));});
test('provider exceptions sanitized and no fallback bucket',async()=>{const f=fixture();f.transport.download=async()=>{throw Error('secret URL/token')};await assert.rejects(f.store.download(locator,meta),e=>code('unavailable')(e)&&!String(e).includes('secret'));});
