'use client';

import React from 'react';
import { Sparkles } from 'lucide-react';
import CreativeAiInsightCard from '@/components/CreativeAiInsightCard';
import type { PrepassFocus, PrepassFocusInsight } from '@/services/analytics';

const FOCUS_LABELS: Record<PrepassFocus, string> = {
  SMB: 'SMB — Small & Mid-Size Fleets',
  ABM: 'ABM — Enterprise Accounts',
  FD360: 'FD360 — FleetDrive 360',
};

function fmtAsOf(asOf: string): string {
  if (!asOf) return '';
  const d = new Date(`${asOf}T00:00:00`);
  if (Number.isNaN(d.getTime())) return asOf;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

// PrePass "Ad Analysis" tab. Surfaces the daily vision-workflow output — one
// AI Creative Insight per focus (SMB / ABM / FD360) — mirroring Spartaco's Ad
// Analysis layout. Each card is generated by analyzing the actual ad creatives
// (images & video frames) from the last 30 days, weighing creatives by MQLs
// driven vs spend.
export default function PrepassCreativeAnalysisClient({
  insights,
}: {
  insights: PrepassFocusInsight[];
}) {
  const latestAsOf = insights
    .map((i) => i.insight?.asOf || '')
    .filter(Boolean)
    .sort()
    .pop() ?? '';

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-brand-dark">Ad Analysis</h1>
        <p className="text-sm text-gray-400 font-medium mt-1">
          AI creative strategy across PrePass focuses
        </p>
      </div>

      {/* Vision insights banner */}
      <div className="rounded-[2rem] border border-gray-100 bg-white shadow-sm overflow-hidden">
        <div className="flex items-center justify-between gap-4 px-8 py-6">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-brand-forest/10 text-brand-forest">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-brand-dark">AI Creative Insights</h3>
              <p className="text-sm text-gray-400 font-medium mt-0.5">
                Generated daily by analyzing the actual ad creatives — images &amp; video frames — from
                the last 30 days, weighing creatives by MQLs driven vs spend. See each focus below.
              </p>
            </div>
          </div>
          {latestAsOf && (
            <span className="text-xs font-medium text-gray-400 shrink-0">as of {fmtAsOf(latestAsOf)}</span>
          )}
        </div>
      </div>

      {/* Per-focus insight cards */}
      <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        {insights.map(({ focus, insight }) => (
          <div key={focus} className="space-y-3">
            <div className="flex items-center gap-2">
              <span className="text-[11px] font-bold uppercase tracking-widest text-white bg-brand-forest px-2.5 py-1 rounded-full">
                {focus}
              </span>
              <span className="text-sm font-semibold text-brand-dark">{FOCUS_LABELS[focus]}</span>
            </div>
            {insight ? (
              <CreativeAiInsightCard insight={insight} />
            ) : (
              <div className="rounded-2xl border border-gray-100 bg-white p-5 text-sm text-gray-400">
                No insight generated yet for this focus. Check back after the next daily run.
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
