import type {Scene,Ratio} from './model.ts';
export const isComparisonConcept=(id:string)=>id==='same-client-two-replies'||id==='build-or-partner-note';
export function renderComparisonHtml(scene:Scene,ratio:Ratio){
 if(ratio!=='1:1'&&ratio!=='4:5')throw new Error('Comparison concepts support Meta feed only');
 const tall=ratio==='4:5',height=tall?1350:1080,thread=scene.template==='same-client-two-replies';
 const terms=`<footer data-qa-box><p data-text>Free audit + media plan · Management starts at $995</p><p class="small" data-text>Pay when campaigns go live, after explicit launch approval.<br>Ad spend separate. No obligation to launch.</p><p class="cta" data-text>Get my free audit + media plan</p></footer>`;
 const body=thread?`<p class="context" data-text>Illustrative scenario: an agency without in-house paid media.</p><section class="incoming" data-qa-box><p class="speaker" data-text>Your client</p><p class="bubble gray" data-text>Can you manage our ads too?</p></section><div class="columns"><section data-qa-box><h2 data-text>WITHOUT A<br>PAID MEDIA TEAM</h2><p class="speaker" data-text>Your agency</p><p class="bubble gray" data-text>We’d need to find someone for that.</p></section><section data-qa-box><h2 data-text>WITH EIC<br>WHITE-LABEL</h2><p class="speaker" data-text>Your agency</p><p class="bubble blue" data-text>Yes. We can handle that.</p><p class="support" data-text>Your brand. Your client.<br>Our paid media team.</p></section></div>${terms}`:`<div class="chrome" data-text>‹ Notes <span>•••</span></div><h1 data-text>Adding paid media<br>to your agency</h1><div class="columns checklist"><section data-qa-box><h2 data-text>Build it in-house</h2><ul><li data-text>Recruit media-buying talent</li><li data-text>Build campaign workflows</li><li data-text>Set up reporting</li></ul></section><section data-qa-box><h2 data-text>Partner with EIC</h2><ul><li data-text>Use EIC’s paid media team</li><li data-text>Start with a free audit + plan</li><li data-text>Dashboard, weekly updates + live chat</li></ul></section></div><p class="joint" data-text>Keep the client relationship under your brand.</p>${terms}`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Agency operating choices · illustrative draft</title><style>*{box-sizing:border-box}html,body{margin:0;width:1080px;height:${height}px;overflow:hidden;background:#fff;color:#24262a;font-family:Arial,'Liberation Sans',sans-serif}#art{width:1080px;height:${height}px;padding:76px;display:flex;flex-direction:column}p{margin:0}.context{font-size:25px;line-height:1.4;color:#62676f;margin-bottom:${tall?60:38}px}.speaker{font-size:26px;color:#646970;margin-bottom:14px}.incoming{margin-bottom:${tall?64:40}px}.bubble{font-size:37px;line-height:1.25;padding:24px 26px;border-radius:28px;width:fit-content}.gray{background:#ececef;border-bottom-left-radius:7px}.blue{background:#087bf5;color:white;border-bottom-right-radius:7px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:46px}.columns>section{min-width:0}h2{font-size:27px;line-height:1.3;margin:0 0 25px;font-weight:600}.support{font-size:27px;line-height:1.4;margin-top:24px;color:#555b63}footer{margin-top:auto;padding-top:30px;border-top:1px solid #e5e5e8;font-size:27px;line-height:1.4}.small{font-size:24px;color:#646970;margin-top:13px}.cta{font-size:28px;font-weight:600;margin-top:22px}.chrome{color:#98730d;display:flex;justify-content:space-between;font-size:29px;border-bottom:1px solid #ecebe6;padding-bottom:24px}h1{font-size:49px;line-height:1.12;letter-spacing:-1px;margin:${tall?62:32}px 0 ${tall?57:36}px}.checklist h2{font-size:31px;margin-bottom:23px}ul{padding:0;margin:0;list-style:none}li{position:relative;padding-left:40px;font-size:29px;line-height:1.35;margin-bottom:25px}li:before{content:'';position:absolute;left:0;top:6px;width:24px;height:24px;border:2px solid #bd9e37;border-radius:50%}.joint{font-size:29px;line-height:1.4;margin-top:${tall?55:25}px;margin-bottom:25px}</style></head><body><main id="art">${body}</main></body></html>`;
}
