import { z } from 'zod';
import { REFERENCE_CATALOG, safeReferenceUrl } from './reference-catalog.ts';
import type { Idea } from './ideas.ts';
const text=z.string().max(2000);
const Fields=z.object({statement:text,sourceUrl:z.string().max(2000).refine(v=>!v||safeReferenceUrl(v)),reviewNote:text,inputs:z.array(text).max(20),route:z.enum(['enter','saved','research','unsure']),confirmedFingerprint:z.string().max(15000).optional()}).strict();
type FieldsType=z.infer<typeof Fields>;
function fingerprint(d:FieldsType){return JSON.stringify([d.statement,d.sourceUrl,d.reviewNote,d.inputs]);}
export const DevelopmentSchema=Fields.superRefine((d,c)=>{if(d.confirmedFingerprint&&(d.confirmedFingerprint!==fingerprint(d)||!d.statement.trim()||!d.sourceUrl||!d.reviewNote.trim()))c.addIssue({code:'custom',message:'Confirmation must match current claim, source and review'});});
export type Development=z.infer<typeof DevelopmentSchema>;
export function directionKind(id:string){if(id==='da-05')return 'documented evidence story';if(['da-02','da-03'].includes(id))return 'confirmed next-step offer';if(['ai-task-walkthrough','ai-mechanism-demo','ve-apple-demonstration','ve-p0-14','da-01','da-04','da-06'].includes(id))return 'approved artifact process demo';return 'problem-recognition visual';}
export function developmentReference(id:string){const r=REFERENCE_CATALOG.find(r=>r.id===id);if(!r||id==='ve-p1-9')throw Error('Reference is not an adoptable direction');return r;}
export function developDirection(idea:Idea,id:string):Idea {const r=developmentReference(id);return {...idea,activeDevelopment:id,developments:{...idea.developments,[id]:idea.developments?.[id]??{statement:'',sourceUrl:'',reviewNote:'',inputs:r.requiredInputs.map(()=>''),route:'enter'}}};}
export function updateDevelopment(idea:Idea,patch:Partial<Development>):Idea {const id=idea.activeDevelopment;if(!id)throw Error('Choose a direction');const current=idea.developments![id];const next={...current,...patch};if(fingerprint(current)!==fingerprint(next))delete next.confirmedFingerprint;return {...idea,developments:{...idea.developments,[id]:DevelopmentSchema.parse(next)}};}
export function confirmDevelopment(idea:Idea):Idea {const d=idea.developments![idea.activeDevelopment!];return updateDevelopment(idea,{confirmedFingerprint:fingerprint(d)});}
export function developmentBrief(idea:Idea):string {
 const id=idea.activeDevelopment;if(!id)return '';const r=developmentReference(id);const d=DevelopmentSchema.parse(idea.developments![id]);
 const unresolved=[...r.requiredInputs.filter((_,n)=>!d.inputs[n]?.trim()).map(s=>`Missing input: ${s}`),...(!d.confirmedFingerprint?['Claim/source/permission review not confirmed by user']:[]),...r.evidenceRequirements.map(s=>`Evidence review required (not independently verified): ${s}`)];
 return [`# Development brief — ${r.title}`,`Direction: ${directionKind(id)}`,`Goal: ${idea.goal}`,`Audience: ${idea.audience||'Unresolved'}`,`Stage: ${idea.stageOverride||(idea.awareness==='unknown'?'Unresolved':idea.awareness==='new'||idea.goal==='recognition'?'Awareness':idea.goal==='action'&&idea.awareness==='ready'?'Action':idea.goal==='trust'||idea.goal==='objection'?'Desire':'Interest')}`,`Business context: ${idea.business||'Not supplied'}`,'## Proposed adaptation — external inspiration, NOT EIC facts',r.adaptationForEIC,'## Actual user inputs',...r.requiredInputs.map((s,n)=>`${s}\n${d.inputs[n]||'[Unresolved]'}`),`Claim (${d.confirmedFingerprint?'User-confirmed — not independently verified':'User-supplied — unconfirmed'}): ${d.statement||'[Unresolved]'}`,`Source: ${d.sourceUrl||'[Unresolved]'}`,`User review / permission note: ${d.reviewNote||'[Unresolved]'}`,'## Unresolved evidence',...unresolved,'## Production handoff',`Communication job: ${r.communicationJob}`,`Visual treatment: ${r.visualTreatment}`,...r.claimConstraints,'Render status: Planning brief only. No artwork rendered, production approval granted, or artwork export created. Bespoke renderer and production review required.','## Reference receipts — not evidence of EIC claims',...r.sources.map(s=>`${s.title}: ${s.url} — ${s.limitations}`),...(d.route==='research'?['## Research brief — generated checklist, NOT live research',`Find first-party evidence for: ${d.statement||r.communicationJob}`,...r.evidenceRequirements,'Record source URL, exact supported wording, date, scope and reuse permission. Have a human review before confirming.']:[])].join('\n\n');
}
