import { type Scene, type Ratio, PLACEMENTS } from './model.ts';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderEditableHtml(scene:Scene,ratio:Ratio):string {
 if(!['1:1','4:5'].includes(ratio))throw Error('Editable content supports Meta feed only');
 const c=scene.content;if(!c)throw Error('Structured content required');
 const p=PLACEMENTS[ratio];
 const body=c.kind==='note'?`<p class="body" data-text>${esc(c.body)}</p>`:`<table data-qa-box><thead><tr><th></th><th data-text>${esc(c.leftHeading)}</th><th data-text>${esc(c.rightHeading)}</th></tr></thead><tbody>${c.rows.map(r=>`<tr><th data-text>${esc(r.label)}</th><td data-text>${esc(r.left.text)}</td><td data-text>${esc(r.right.text)}</td></tr>`).join('')}</tbody></table>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Editable creative draft</title><style>*{box-sizing:border-box}html,body{margin:0;width:${p.width}px;height:${p.height}px;color:#202320;font-family:Arial,sans-serif}#art{width:100%;height:100%;padding:${Math.max(64,p.insetY)}px ${Math.max(64,p.insetX)}px;background:#fff}#safe{height:100%;display:flex;flex-direction:column;gap:28px}h1{font-size:56px;line-height:1.12;margin:0;white-space:pre-line;overflow-wrap:normal}.body{font-size:32px;line-height:1.42;white-space:pre-wrap;margin:0;overflow-wrap:normal}table{border-collapse:collapse;width:100%;table-layout:fixed;font-size:25px;line-height:1.3}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #b9c8bf;padding:16px 12px;overflow-wrap:normal;word-break:normal}th:first-child{width:28%;font-size:24px}thead{background:#edf2ed}footer{margin-top:auto;font-size:30px;font-weight:bold;overflow-wrap:normal}.disclosure{font-size:18px;line-height:1.3;margin:0}</style></head><body><main id="art"><div id="safe"><h1 data-text>${esc(scene.headline)}</h1>${body}<footer data-text>${esc(scene.cta)}</footer><p class="disclosure" data-text>${c.kind==='note'?'Draft note · user-authored, not a testimonial.':'Illustrative comparison · proposed capabilities, not verified facts. Not a universal competitor assessment.'}</p></div></main></body></html>`;
}
