import type { Scene, Ratio } from './model.ts';
import type { RenderAssets } from './render.ts';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderMathHtml(scene:Scene,ratio:Ratio,assets:RenderAssets){
 if(ratio!=='1:1'&&ratio!=='4:5')throw new Error('One-Client Math supports Meta feed only');
 const h=ratio==='1:1'?1080:1350,extra=h-1080;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; font-src data:; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><style>
 @font-face{font-family:Montserrat;src:url('${assets.fontData}');font-weight:100 900}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:${h}px;overflow:hidden;font-family:Montserrat,Arial,sans-serif;color:#123f30}#art{width:1080px;height:${h}px;background:#f4f1e7;padding:72px 72px;position:relative}header{display:flex;align-items:center;justify-content:space-between;${scene.logoPosition==='right'?'flex-direction:row-reverse;':''}}.logo{width:142px;height:64px;object-fit:contain}h1{margin:0;font-size:${32*scene.headlineScale}px;line-height:1.18;white-space:pre-line;font-weight:600;max-width:600px}.equation{margin-top:${30+extra/3}px;position:relative}.row{display:flex;align-items:center;gap:26px;height:130px}.number{font-size:120px;letter-spacing:-8px;font-weight:600;line-height:1.3;min-width:555px;white-space:nowrap}.operator{display:inline-block;width:70px;font-weight:400}.note{font-size:26px;line-height:1.35;max-width:320px}.note small{font-size:23px}.sub{transform:rotate(-2deg);border-bottom:4px solid #123f30;padding-bottom:14px;height:140px}.answer{margin-top:16px;height:140px;color:#00775b}.answer .number{font-size:124px;letter-spacing:-8px}.answer .note{border-left:4px solid #e84c00;padding-left:15px}.caution{font-size:28px;font-weight:600;line-height:1.4;margin-top:20px}.caution span{font-weight:400;font-size:25px}.offer{position:absolute;bottom:72px;left:72px;right:72px;border-top:1px solid #97a99d;padding-top:24px}.brand{font-size:27px;font-weight:600;margin:0 0 12px}.cta{font-size:36px;font-weight:600;letter-spacing:-1px;margin:0 0 17px;color:#00775b}.terms{font-size:25px;line-height:1.5;margin:0}.terms b{font-weight:600}
 </style></head><body><main id="art"><header data-qa-box><img class="logo" src="${assets.logoData}" alt="EIC"><h1 data-text>${escape(scene.headline)}</h1></header><section class="equation" aria-label="Illustrative monthly fee difference"><div class="row"><div class="number" data-text><span class="operator"></span>$3,000</div><div class="note" data-text>/mo client fee<br><small>Illustrative pricing</small></div></div><div class="row sub"><div class="number" data-text><span class="operator">−</span>$995</div><div class="note" data-text>/mo fulfillment<br><small>Management starts here</small></div></div><div class="row answer"><div class="number" data-text><span class="operator">=</span>$2,005</div><div class="note" data-text>/mo difference<br><small>Before other costs</small></div></div><div class="caution" data-text>Illustrative. Not guaranteed.<br><span>Not net profit or ROI. Ad spend separate.</span></div></section><section class="offer" data-qa-box><p class="brand" data-text>Your agency brand. Our white-label team.</p><p class="cta" data-text>${escape(scene.cta)} ↗</p><p class="terms" data-text><b>Free audit + custom media plan. No obligation.</b><br>Pay only after explicit launch approval.</p></section></main></body></html>`;
}
