import type {Scene,Ratio} from './model.ts';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const isNativeConcept=(id:string)=>id==='agency-owner-text-thread'||id==='founder-note';
export function renderNativeHtml(scene:Scene,ratio:Ratio){
 if(ratio!=='1:1'&&ratio!=='4:5')throw new Error('Native concepts support Meta feed only');
 const portrait=ratio==='4:5',height=portrait?1350:1080;
 const thread=scene.template==='agency-owner-text-thread';
 const bubble=(text:string,out=false)=>`<p data-text class="bubble ${out?'out':'in'}">${esc(text)}</p>`;
 const body=thread?`<div class="meta" data-text>Illustrative conversation</div><section class="exchange" data-qa-box><div class="recipient" data-text>Your client</div>${bubble('Can you manage our ads too?')}</section><section class="exchange private" data-qa-box><div class="recipient" data-text>EIC · private agency conversation</div>${bubble('Can you handle paid media under our brand?',true)}${bubble('Yes. Free audit + media plan first. Management starts at $995. You keep the client.')}</section><section class="exchange" data-qa-box><div class="recipient" data-text>Your client · back to your conversation</div>${bubble('Yes. We can handle that.',true)}</section><div class="terms" data-text>Pay only after your approval, when campaigns go live.<br>Ad spend separate. No obligation to launch.</div>`:`<div class="chrome" data-text>‹ Notes <span>•••</span></div><article data-qa-box><p class="byline" data-text>EIC / Agency notes</p><h1 data-text>${esc(scene.headline)}</h1><p class="lead" data-text>You don’t need to hire an ads department to say yes.</p><p data-text>We handle paid media under your brand.<br>You keep the client.</p><ul><li data-text>Free audit</li><li data-text>Free custom media plan</li><li data-text>Management starts at $995</li></ul><p class="payment" data-text>Pay when campaigns go live,<br>after your approval.</p><p class="small" data-text>Ad spend separate. No obligation to launch.</p><p class="closing" data-text>${esc(scene.cta)}</p></article>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><style>*{box-sizing:border-box}html,body{margin:0;width:1080px;height:${height}px;overflow:hidden;background:#fff;color:#202124;font-family:Arial,'Liberation Sans',sans-serif}#art{width:1080px;height:${height}px;padding:76px 76px;position:relative}p{margin:0}.meta{font-size:26px;color:#666a70;margin-bottom:${portrait?46:28}px}.exchange{display:flex;flex-direction:column;gap:16px;margin-bottom:${portrait?44:24}px}.recipient{font-size:27px;font-weight:600;color:#62666c;padding-bottom:10px;border-bottom:1px solid #e5e5e8}.bubble{font-size:35px;line-height:1.28;border-radius:29px;padding:21px 27px;max-width:790px;width:fit-content}.in{background:#e9e9eb;border-bottom-left-radius:8px}.out{background:#087bf5;color:white;align-self:flex-end;border-bottom-right-radius:8px}.terms{font-size:25px;line-height:1.5;color:#64676c;margin-top:${portrait?42:26}px}.chrome{color:#a77c0b;font-size:29px;display:flex;justify-content:space-between;padding-bottom:27px;border-bottom:1px solid #e9e9e7}.chrome span{letter-spacing:3px}article{padding-top:${portrait?48:30}px}article p{font-size:34px;line-height:1.4}.byline{font-size:25px!important;color:#747474;margin-bottom:22px}h1{font-size:${48*scene.headlineScale}px;line-height:1.14;letter-spacing:-1.1px;margin:0 0 29px;max-width:860px;white-space:pre-line}.lead{margin-bottom:25px}ul{padding:0;margin:30px 0;list-style:none}li{font-size:34px;line-height:1.45;margin:10px 0;padding-left:49px;position:relative}li:before{content:'';width:27px;height:27px;border:2px solid #b69738;border-radius:50%;position:absolute;left:0;top:10px}.small{font-size:25px!important;color:#64676c;margin-top:18px}.closing{margin-top:${portrait?56:28}px;font-weight:600} </style></head><body><main id="art" class="${thread?'thread':'note'}">${body}</main></body></html>`;
}
