import test from 'node:test';
import assert from 'node:assert/strict';
import { PublicationBindingSchema, evaluatePerformanceEvidence, type PublicationBinding, type PerformanceEvidence, type TrustedPerformanceContext } from './performance-linkage.ts';

// Entirely synthetic fixtures: no live account, source, outcome or verification claims.
function fixture() {
 const binding: PublicationBinding = { id:'synthetic-binding',tenantId:'eicagency',ownerId:'synthetic-owner',projectId:'synthetic-project',versionId:'synthetic-version',assetId:'synthetic-export',placementId:'meta-feed',assetSha256:'a'.repeat(64),recipeSha256:'b'.repeat(64),platform:'meta',accountId:'synthetic-account',campaignId:'synthetic-campaign',adSetId:'synthetic-adset',adId:'synthetic-ad',creativeId:'synthetic-creative',validFrom:'2026-09-01T00:00:00Z',validTo:'2026-10-01T00:00:00Z',claim:'operator_claim' };
 const evidence: PerformanceEvidence = { id:'synthetic-evidence',bindingId:binding.id,lane:'first_party_observed',kind:'delivery',tenantId:binding.tenantId,platform:binding.platform,accountId:binding.accountId,adId:binding.adId,creativeId:binding.creativeId,window:{start:'2026-09-20T00:00:00Z',end:'2026-09-21T00:00:00Z',timezone:'UTC',currency:'USD',dateBasis:'exposure_cohort',attributionSettingsId:'synthetic-settings',cohortId:'synthetic-cohort'},source:{system:'synthetic-native',revision:'synthetic-revision',manifestSha256:'c'.repeat(64),rowIds:['synthetic-row']},monetaryGrains:[],outcomes:[] };
 const context: TrustedPerformanceContext = { tenantId:binding.tenantId,ownerId:binding.ownerId,accounts:[{platform:binding.platform,accountId:binding.accountId}],versions:[{projectId:binding.projectId,versionId:binding.versionId,assetId:binding.assetId,placementId:binding.placementId,assetSha256:binding.assetSha256,recipeSha256:binding.recipeSha256}],registryComplete:true,bindings:[binding],verifiedPublications:[{binding,verificationRef:'synthetic-upload-review'}],verifiedEvidence:[{evidence,confirmations:{delivery:'synthetic-native-review',settings:'synthetic-settings-review',coverage:'synthetic-coverage-review'}}] };
 return {binding,evidence,context};
}
const evaluate=(f:ReturnType<typeof fixture>)=>evaluatePerformanceEvidence(f.binding,f.evidence,f.context);
test('synthetic verified delivery eligible only for descriptive review; never winner',()=>{const r=evaluate(fixture());assert.equal(r.eligibleForRequestedReview,true);assert.equal(r.automaticWinner,false);assert.equal(r.performanceLearningEnabled,false);});
test('operator claim alone cannot verify delivery',()=>{const f=fixture();f.context.verifiedPublications=[];assert.ok(evaluate(f).blockers.includes('publication_not_verified'));});
test('missing trusted context fails closed',()=>{const f=fixture();assert.equal(evaluatePerformanceEvidence(f.binding,f.evidence,undefined).eligibleForRequestedReview,false);});
for(const field of ['tenantId','accountId','versionId','assetSha256','ownerId'] as const)test(`rejects tampered binding ${field}`,()=>{const f=fixture();f.binding={...f.binding,[field]:field==='assetSha256'?'d'.repeat(64):'other'};assert.equal(evaluate(f).eligibleForRequestedReview,false);});
test('rejects external inspiration even with trusted snapshot',()=>{const f=fixture();f.evidence.lane='external_inspiration';assert.ok(evaluate(f).blockers.includes('not_first_party_observed'));});
test('strict schema rejects client verified flag',()=>{assert.equal(PublicationBindingSchema.safeParse({...fixture().binding,verified:true}).success,false);});
test('overlapping ad reused with different creative is ambiguous',()=>{const f=fixture();f.context.bindings.push({...f.binding,id:'other',creativeId:'other'});assert.ok(evaluate(f).blockers.includes('ambiguous_ad_binding'));});
test('duplicate binding identifiers fail',()=>{const f=fixture();f.context.bindings.push({...f.binding});assert.ok(evaluate(f).blockers.includes('duplicate_binding_id'));});
test('incomplete registry fails',()=>{const f=fixture();f.context.registryComplete=false;assert.equal(evaluate(f).eligibleForRequestedReview,false);});
for(const field of ['currency','timezone','start','attributionSettingsId'] as const)test(`missing window ${field} fails`,()=>{const f=fixture();delete (f.evidence.window as Record<string,unknown>)[field];assert.equal(evaluate(f).eligibleForRequestedReview,false);});
test('duplicate source row identifiers fail',()=>{const f=fixture();f.evidence.source.rowIds.push('synthetic-row');assert.equal(evaluate(f).eligibleForRequestedReview,false);});
test('partial publication-window coverage fails',()=>{const f=fixture();f.evidence.window.end='2026-10-02T00:00:00Z';assert.ok(evaluate(f).blockers.includes('outside_publication_window'));});
test('outcomes need provenance and qualified business definition',()=>{const f=fixture();f.evidence.kind='attributed_conversions';assert.ok(evaluate(f).blockers.includes('qualified_outcomes_missing'));});
test('ROI cannot be derived from delivery or assertion alone',()=>{const f=fixture();f.evidence.kind='profit_roi';assert.ok(evaluate(f).blockers.includes('costs_not_verified'));assert.ok(evaluate(f).blockers.includes('refunds_not_verified'));});
test('synthetic attributed conversions require all scoped confirmations',()=>{const f=fixture();f.evidence.kind='attributed_conversions';f.evidence.outcomes=[{id:'synthetic-outcome',sourceRevision:'r1',provenanceRef:'synthetic-crm',definitionId:'qualified-lead-v1',touchpointId:'synthetic-touch',credit:1}];Object.assign(f.context.verifiedEvidence[0].confirmations,{outcomes:'synthetic-crm-review',attribution:'synthetic-credit-review',cohort:'synthetic-maturity-review'});assert.equal(evaluate(f).eligibleForRequestedReview,true);});
test('incompatible monetary grains fail, even if asserted verified',()=>{const f=fixture();f.evidence.monetaryGrains=[{role:'media',currency:'EUR',timezone:'UTC',dateBasis:'exposure_cohort',cohortId:'synthetic-cohort',start:f.evidence.window.start,end:f.evidence.window.end,attributionSettingsId:'synthetic-settings',grain:'ad_window'}];assert.ok(evaluate(f).blockers.includes('incompatible_monetary_grain'));});
test('evidence changed after verification fails',()=>{const f=fixture();f.context=structuredClone(f.context);f.evidence.source.revision='new';assert.ok(evaluate(f).blockers.includes('evidence_not_verified'));});
test('causal ROI requires causal design independently of attribution',()=>{const f=fixture();f.evidence.kind='incremental_roi';assert.ok(evaluate(f).blockers.includes('causal_design_not_verified'));});
