export const SOURCES = [
 {id:'brief-v2',title:'Build Brief v2',url:'https://docs.google.com/document/d/1iWyFSiVzlwyglOandPj66w97F3Wb5AT-YcXSCnNXHbA/edit',role:'Product requirements',note:'Application-owned credentials, persisted jobs, Chromium, approval gates. Internal build approved; deployment is not.'},
 {id:'blueprint',title:'EIC Marketing Funnel Blueprint',url:'https://drive.google.com/file/d/1kqhkyjILI_NiZYQmHPzDNwPAEjI5-Qy0/view',role:'Canonical strategy',note:'Awareness introduces; Interest educates; Desire provides social proof; Action asks for conversion. Downloaded reference has 15 pages.'},
 {id:'transcript',title:'Creative funnel transcript',url:'https://drive.google.com/file/d/1S3Tr4mFd1QuB1xEw_j-N5vKeR_ZlHVBb/view',role:'Supporting explanation',note:'Relationship before the sale; permission for UGC; internal data may support proof; value-add offers instead of automatic discounting.'},
 {id:'brand-guide',title:'EIC Brand Guide v1.0',url:'https://drive.google.com/file/d/1FqGEPZFOV-06R8H715cpO0q-cR8ito46/view',role:'Logo system',note:'Preserve original primary mark, proportions and clear space. Selected primary logo is the unchanged repository original, visually matched to this guide.'},
 {id:'brand-sheet',title:'EIC branding sheet',url:'https://drive.google.com/file/d/11jVB9eRMbk6mLsw2a3iwO29HknDfYt8S/view',role:'Creative typography and palette',note:'Montserrat regular/semibold; jade #009C77, orange #E84C00, gray #9FA1A0. Original logo colors are not recolored to match.'},
 {id:'launch-tracker',title:'05 | Paid Media Launch Tracker',url:'https://app.clickup.com/t/86bc7h762',role:'Reference concept, not a proven winner',note:'Native order-tracker treatment. Updated to show owner-approved forecast, ads/tracking build and approval-before-payment sequence.'},
 {id:'owner-offer',title:'Dustin’s approved offer clarification',url:'https://app.slack.com/archives/D0BPN2R9Z0B/p1790385016581779',role:'Offer authority',note:'Free media plan + forecast, campaign setup, ads and tracking. No obligation. Review on launch call; charge on launch approval. Ad spend separate.'},
] as const;
export function sourcesForConcept(template:string) {
 if(template==='same-client-two-replies'||template==='build-or-partner-note')return [...SOURCES.filter(s=>s.id!=='launch-tracker'),{id:template,title:'What Agencies Think vs. Reality · comparison adaptation',url:'https://app.clickup.com/t/86bc7h76j',role:'Parent-verified live task summary + user-directed adaptation; not performance evidence',note:'Original task contrasts building a paid media operation with a white-label partner. User requested with/without comparison using clearer native messages and Notes. Same client asks once; both replies are explicitly Your agency. Checklist presents alternative operating choices, not universal hiring requirements or savings. Illustrative copy, no real messages or outcomes.'},{id:'white-label-parent',title:'White-label parent offer',url:'https://app.clickup.com/t/86bc7h74y',role:'Parent-verified offer scope',note:'Agency owns client under its brand. Free audit + custom media plan; management starts $995. Pay when campaigns go live only after explicit launch approval. Ad spend separate; no obligation. Dashboard, weekly updates and live chat are service features, not results. Native system typography and minimal branding are user-directed.'}];
 if(template==='agency-owner-text-thread'||template==='founder-note')return [...SOURCES.filter(s=>s.id!=='launch-tracker'),{id:template,title:template==='founder-note'?'Founder Note · draft':'Agency Owner Text Thread · illustrative',url:'https://app.clickup.com/t/'+(template==='founder-note'?'86bc7h75z':'86bc7h75n'),role:'Parent-verified live task summary; suggested copy, not an actual exchange',note:template==='founder-note'?'No need to hire an ads department. Free audit + custom media plan; management starts $995. Pay on approved launch. Bring us one client. Native notes recreation, not a historical founder message.':'Client asks agency to manage ads; agency privately asks EIC for white-label support, then answers client yes. Two separate private exchanges, shown chronologically. Illustrative, not a testimonial. Free audit + media plan; management starts $995.'},{id:'white-label-parent',title:'White-label parent offer',url:'https://app.clickup.com/t/86bc7h74y',role:'Parent task scope',note:'Agency owns the client under its own brand. No obligation. Ad spend separate. Payment only on explicit approval when campaigns go live. Native system typography intentionally replaces campaign typography; no simulated identity or historical screenshot.'}];
 if(template!=='one-client-math') return SOURCES;
 return [...SOURCES.filter(s=>s.id!=='launch-tracker'),
 {id:'one-client-math',title:'One-Client Math · task concept',url:'https://app.clickup.com/t/86bc7h76e',role:'Source task, not performance evidence',note:'Parent-verified task summary: illustrative $3,000/mo client fee minus fulfillment starting $995/mo = $2,005/mo before other costs. Not profit or ROI; illustrative, not guaranteed. CTA: Map My First Client.'},
 {id:'white-label-parent',title:'White-label offer · parent task',url:'https://app.clickup.com/t/86bc7h74y',role:'Parent task scope',note:'Agency brand; free audit + custom media plan. No obligation; pay only after explicit launch approval. Ad spend separate; management starts $995/mo.'}];
}
export const SOURCE_WARNINGS = [
 'Brand review: supplied sheet uses Montserrat/jade/orange; dashboard and v2 rendering notes use Inter/forest/orange. This ad draft follows the supplied sheet, while the app shell stays unchanged. Dustin must confirm before release.',
 'Logo review: this draft uses the unchanged rectangular primary mark already in the repository, which matches the logo-system guide. The folder also contains older/special marks; no automatic substitution is allowed.',
 'Framework nuance: the deck separates Interest (education) from Desire (social proof); the transcript overlaps proof across both. This beta preserves the deck distinction.',
 'Source discrepancy: this downloaded Blueprint has 15 pages, although v2 refers to a 16-page deck. No missing slide has been invented.',
 'No performance claims, customer messages, reviews, results or guarantees are invented. This concept has no performance history.',
 'Safe zones are conservative draft margins, not certified platform placement rules. Human review of every selected pack placement is required.',
 'Static assets only: no video, publishing, platform acceptance guarantee or complete Performance Max readiness. Google images are abstract planning illustrations, not product screenshots or evidence; text assets are supplied separately.',
 'Banner copy is intentionally condensed by placement. The 320 × 50 asset contains only the original logo and “Free media plan.”; review the destination and separately supplied offer conditions before release.',
] as const;
